# Generated by Django 3.1.14 on 2024-10-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('carousal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextCardPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='carousal_textcardpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plugin_images/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='carousel',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
